apiVersion: v1
kind: Pod
metadata:
  name: zammad
spec:
  volumes:
  - name: cache-volume
    emptyDir: {}
  containers:
  - name: zammad-scheduler
    image: monotek/zammad-docker-compose:zammad
    args: [ "zammad-scheduler" ]
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /opt/zammad/tmp
      name: cache-volume
  - name: zammad-railsserver
    image: monotek/zammad-docker-compose:zammad
    imagePullPolicy: Always
    args: ["zammad-railsserver"]
    ports:
    - containerPort: 3000
      name: railsserver
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /opt/zammad/tmp
      name: cache-volume
  - name: zammad-websocket
    image: monotek/zammad-docker-compose:zammad
    args: [ "zammad-websocket" ]
    ports:
    - containerPort: 6042
      name: websocket
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /opt/zammad/tmp
      name: cache-volume
