apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zammad-nginx
  namespace: zammad
  labels:
    component: nginx
    app: zammad
spec:
  serviceName: zammad-nginx
  replicas: 1
  template:
    metadata:
      labels:
        component: nginx
        app: zammad
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zammad-nginx
        image: monotek/zammad-docker-compose:zammad
        args: [ "zammad-nginx" ]
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 6042
          name: nginx-ws
        imagePullPolicy: Always
